"""entidades da fase 1

Revision ID: 0002
Revises: 0001
Create Date: 2026-08-12 21:03:41.024157+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

#: Tipos ENUM nativos criados implicitamente por op.create_table(). Precisam ser
#: removidos à mão no downgrade.
TIPOS_ENUM = (
    "papel",
    "origem_sessao_login",
    "tipo_token",
    "conselho",
    "status_cadastro",
    "status_agendamento",
    "status_sessao",
    "tipo_evento_sessao",
    "slug_plano",
    "status_compra",
    "status_credito",
    "metodo_pagamento",
    "status_pagamento",
    "tipo_termo",
    "canal_notificacao",
    "status_notificacao",
    "tipo_pontuacao",
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "especialidades",
        sa.Column("slug", sa.String(length=60), nullable=False),
        sa.Column("nome", sa.String(length=120), nullable=False),
        sa.Column("descricao", sa.Text(), nullable=True),
        sa.Column("categoria", sa.String(length=60), nullable=True),
        sa.Column("ativo", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("ordem_exibicao", sa.Integer(), server_default="100", nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "criado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "atualizado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_especialidades")),
        sa.UniqueConstraint("slug", name=op.f("uq_especialidades_slug")),
    )
    op.create_table(
        "logs_auditoria",
        sa.Column("usuario_id", sa.UUID(), nullable=True),
        sa.Column("acao", sa.String(length=80), nullable=False),
        sa.Column("entidade", sa.String(length=60), nullable=True),
        sa.Column("entidade_id", sa.UUID(), nullable=True),
        sa.Column("ip", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("request_id", sa.String(length=40), nullable=True),
        sa.Column("dados_antes", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("dados_depois", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("criado_em", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_logs_auditoria")),
    )
    op.create_index(
        "ix_logs_auditoria_entidade", "logs_auditoria", ["entidade", "entidade_id"], unique=False
    )
    op.create_index(
        "ix_logs_auditoria_usuario_criado",
        "logs_auditoria",
        ["usuario_id", "criado_em"],
        unique=False,
    )
    op.create_table(
        "planos",
        sa.Column(
            "slug", sa.Enum("AVULSO", "PACOTE_5", "PACOTE_10", name="slug_plano"), nullable=False
        ),
        sa.Column("nome", sa.String(length=80), nullable=False),
        sa.Column("descricao", sa.Text(), nullable=True),
        sa.Column("quantidade_sessoes", sa.SmallInteger(), nullable=False),
        sa.Column("validade_dias", sa.SmallInteger(), server_default="180", nullable=False),
        sa.Column(
            "desconto_percentual",
            sa.Numeric(precision=5, scale=2),
            server_default="0",
            nullable=False,
        ),
        sa.Column("ativo", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("ordem_exibicao", sa.Integer(), server_default="100", nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "criado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "atualizado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "desconto_percentual >= 0 AND desconto_percentual < 100",
            name=op.f("ck_planos_desconto_0_100"),
        ),
        sa.CheckConstraint("quantidade_sessoes > 0", name=op.f("ck_planos_quantidade_positiva")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_planos")),
        sa.UniqueConstraint("slug", name=op.f("uq_planos_slug")),
    )
    op.create_table(
        "sintomas",
        sa.Column("slug", sa.String(length=60), nullable=False),
        sa.Column("nome", sa.String(length=120), nullable=False),
        sa.Column("descricao_leiga", sa.String(length=255), nullable=False),
        sa.Column("categoria", sa.String(length=60), nullable=True),
        sa.Column("bandeira_risco", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("ativo", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("ordem_exibicao", sa.Integer(), server_default="100", nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "criado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "atualizado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sintomas")),
        sa.UniqueConstraint("slug", name=op.f("uq_sintomas_slug")),
    )
    op.create_table(
        "termos_versionados",
        sa.Column(
            "tipo",
            sa.Enum(
                "TERMOS_USO",
                "POLITICA_PRIVACIDADE",
                "CONTRATO_PROFISSIONAL",
                "CONSENT_DADOS_SAUDE",
                "CONSENT_TRANSCRICAO",
                name="tipo_termo",
            ),
            nullable=False,
        ),
        sa.Column("versao", sa.SmallInteger(), nullable=False),
        sa.Column("titulo", sa.String(length=200), nullable=False),
        sa.Column("conteudo_md", sa.Text(), nullable=False),
        sa.Column("hash_sha256", sa.String(length=64), nullable=False),
        sa.Column("vigente_desde", sa.DateTime(timezone=True), nullable=False),
        sa.Column("vigente_ate", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "criado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "atualizado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_termos_versionados")),
        sa.UniqueConstraint("tipo", "versao", name="uq_termo_tipo_versao"),
    )
    op.create_index(
        "ix_termos_versionados_tipo_vigente",
        "termos_versionados",
        ["tipo", "vigente_ate"],
        unique=False,
    )
    op.create_table(
        "usuarios",
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("senha_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "papel", sa.Enum("PACIENTE", "PROFISSIONAL", "ADMIN", name="papel"), nullable=False
        ),
        sa.Column("nome_completo", sa.String(length=150), nullable=False),
        sa.Column("telefone_e164", sa.String(length=20), nullable=True),
        sa.Column(
            "timezone", sa.String(length=50), server_default="America/Sao_Paulo", nullable=False
        ),
        sa.Column("ativo", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("email_verificado_em", sa.DateTime(timezone=True), nullable=True),
        sa.Column("telefone_verificado_em", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ultimo_login_em", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "criado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "atualizado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_usuarios")),
        sa.UniqueConstraint("email", name=op.f("uq_usuarios_email")),
    )
    op.create_table(
        "eventos_pontuacao",
        sa.Column("usuario_id", sa.UUID(), nullable=False),
        sa.Column(
            "tipo",
            sa.Enum(
                "PONTUALIDADE_PROFISSIONAL",
                "SESSAO_REALIZADA",
                "AVALIACAO_RESPONDIDA",
                "PERFIL_COMPLETO",
                "CANCELAMENTO_TARDIO",
                "NO_SHOW",
                name="tipo_pontuacao",
            ),
            nullable=False,
        ),
        sa.Column("pontos", sa.Integer(), nullable=False),
        sa.Column("referencia_tipo", sa.String(length=40), nullable=True),
        sa.Column("referencia_id", sa.UUID(), nullable=True),
        sa.Column("descricao", sa.String(length=200), nullable=True),
        sa.Column("criado_em", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["usuario_id"],
            ["usuarios.id"],
            name=op.f("fk_eventos_pontuacao_usuario_id_usuarios"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_eventos_pontuacao")),
        sa.UniqueConstraint("usuario_id", "tipo", "referencia_id", name="uq_pontuacao_idempotente"),
    )
    op.create_index(
        "ix_eventos_pontuacao_usuario", "eventos_pontuacao", ["usuario_id"], unique=False
    )
    op.create_table(
        "notificacoes",
        sa.Column("usuario_id", sa.UUID(), nullable=False),
        sa.Column(
            "canal",
            sa.Enum("EMAIL", "WHATSAPP", "IN_APP", "PUSH", name="canal_notificacao"),
            nullable=False,
        ),
        sa.Column("template", sa.String(length=80), nullable=False),
        sa.Column("destino", sa.String(length=255), nullable=False),
        sa.Column("contexto", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PENDENTE", "ENVIANDO", "ENVIADA", "FALHA", "CANCELADA", name="status_notificacao"
            ),
            server_default="PENDENTE",
            nullable=False,
        ),
        sa.Column("agendada_para", sa.DateTime(timezone=True), nullable=False),
        sa.Column("tentativas", sa.SmallInteger(), server_default="0", nullable=False),
        sa.Column("proxima_tentativa_em", sa.DateTime(timezone=True), nullable=True),
        sa.Column("enviada_em", sa.DateTime(timezone=True), nullable=True),
        sa.Column("provedor_msg_id", sa.String(length=120), nullable=True),
        sa.Column("erro", sa.Text(), nullable=True),
        sa.Column("chave_idempotencia", sa.String(length=120), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "criado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "atualizado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["usuario_id"],
            ["usuarios.id"],
            name=op.f("fk_notificacoes_usuario_id_usuarios"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notificacoes")),
        sa.UniqueConstraint("chave_idempotencia", name=op.f("uq_notificacoes_chave_idempotencia")),
    )
    op.create_index(
        "ix_notificacoes_status_agendada", "notificacoes", ["status", "agendada_para"], unique=False
    )
    op.create_index("ix_notificacoes_usuario", "notificacoes", ["usuario_id"], unique=False)
    op.create_table(
        "perfis_paciente",
        sa.Column("usuario_id", sa.UUID(), nullable=False),
        sa.Column("data_nascimento", sa.Date(), nullable=True),
        sa.Column("cpf_cifrado", sa.LargeBinary(), nullable=True),
        sa.Column("responsavel_legal_nome", sa.String(length=150), nullable=True),
        sa.Column("responsavel_legal_cpf_cifrado", sa.LargeBinary(), nullable=True),
        sa.Column("contato_emergencia_nome", sa.String(length=150), nullable=True),
        sa.Column("contato_emergencia_telefone", sa.String(length=20), nullable=True),
        sa.Column(
            "preferencia_canal_notificacao",
            sa.String(length=20),
            server_default="EMAIL",
            nullable=False,
        ),
        sa.Column("observacoes", sa.Text(), nullable=True),
        sa.Column("pontos_total", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "criado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "atualizado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["usuario_id"],
            ["usuarios.id"],
            name=op.f("fk_perfis_paciente_usuario_id_usuarios"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("usuario_id", name=op.f("pk_perfis_paciente")),
    )
    op.create_table(
        "perfis_profissional",
        sa.Column("usuario_id", sa.UUID(), nullable=False),
        sa.Column("nome_exibicao", sa.String(length=150), nullable=False),
        sa.Column("foto_url", sa.String(length=500), nullable=True),
        sa.Column("conselho", sa.Enum("CRP", "CREFITO", name="conselho"), nullable=False),
        sa.Column("registro_numero", sa.String(length=30), nullable=False),
        sa.Column("registro_uf", sa.String(length=2), nullable=False),
        sa.Column("registro_verificado_em", sa.DateTime(timezone=True), nullable=True),
        sa.Column("registro_verificado_por_id", sa.UUID(), nullable=True),
        sa.Column("descricao", sa.String(length=500), nullable=True),
        sa.Column("duracao_sessao_min", sa.SmallInteger(), nullable=True),
        sa.Column("intervalo_entre_sessoes_min", sa.SmallInteger(), nullable=True),
        sa.Column("limite_horas_dia", sa.SmallInteger(), nullable=True),
        sa.Column(
            "antecedencia_minima_agendamento_h",
            sa.SmallInteger(),
            server_default="2",
            nullable=False,
        ),
        sa.Column(
            "status_cadastro",
            sa.Enum(
                "RASCUNHO",
                "EM_ANALISE",
                "APROVADO",
                "REJEITADO",
                "SUSPENSO",
                name="status_cadastro",
            ),
            server_default="RASCUNHO",
            nullable=False,
        ),
        sa.Column("mp_user_id", sa.String(length=50), nullable=True),
        sa.Column("mp_refresh_token_cifrado", sa.LargeBinary(), nullable=True),
        sa.Column("cpf_cnpj_cifrado", sa.LargeBinary(), nullable=True),
        sa.Column("pontos_total", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "criado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "atualizado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "char_length(registro_uf) = 2", name=op.f("ck_perfis_profissional_uf_2_letras")
        ),
        sa.CheckConstraint(
            "descricao IS NULL OR char_length(descricao) <= 500",
            name=op.f("ck_perfis_profissional_descricao_max_500"),
        ),
        sa.ForeignKeyConstraint(
            ["usuario_id"],
            ["usuarios.id"],
            name=op.f("fk_perfis_profissional_usuario_id_usuarios"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("usuario_id", name=op.f("pk_perfis_profissional")),
        sa.UniqueConstraint(
            "conselho", "registro_uf", "registro_numero", name="uq_registro_conselho"
        ),
    )
    op.create_table(
        "sessoes_login",
        sa.Column("usuario_id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "origem",
            sa.Enum("WEB", "APP", name="origem_sessao_login"),
            server_default="WEB",
            nullable=False,
        ),
        sa.Column("criada_em", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expira_em", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ultimo_acesso_em", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ip", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("revogada_em", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["usuario_id"],
            ["usuarios.id"],
            name=op.f("fk_sessoes_login_usuario_id_usuarios"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sessoes_login")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_sessoes_login_token_hash")),
    )
    op.create_index("ix_sessoes_login_usuario_id", "sessoes_login", ["usuario_id"], unique=False)
    op.create_table(
        "sintomas_especialidades",
        sa.Column("sintoma_id", sa.UUID(), nullable=False),
        sa.Column("especialidade_id", sa.UUID(), nullable=False),
        sa.Column("peso", sa.SmallInteger(), server_default="3", nullable=False),
        sa.CheckConstraint(
            "peso BETWEEN 1 AND 5", name=op.f("ck_sintomas_especialidades_peso_1_5")
        ),
        sa.ForeignKeyConstraint(
            ["especialidade_id"],
            ["especialidades.id"],
            name=op.f("fk_sintomas_especialidades_especialidade_id_especialidades"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["sintoma_id"],
            ["sintomas.id"],
            name=op.f("fk_sintomas_especialidades_sintoma_id_sintomas"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "sintoma_id", "especialidade_id", name=op.f("pk_sintomas_especialidades")
        ),
    )
    op.create_index(
        "ix_sintomas_especialidades_especialidade_id",
        "sintomas_especialidades",
        ["especialidade_id"],
        unique=False,
    )
    op.create_table(
        "tokens_verificacao",
        sa.Column("usuario_id", sa.UUID(), nullable=False),
        sa.Column(
            "tipo", sa.Enum("VERIFICACAO_EMAIL", "RESET_SENHA", name="tipo_token"), nullable=False
        ),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("criado_em", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expira_em", sa.DateTime(timezone=True), nullable=False),
        sa.Column("usado_em", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["usuario_id"],
            ["usuarios.id"],
            name=op.f("fk_tokens_verificacao_usuario_id_usuarios"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tokens_verificacao")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_tokens_verificacao_token_hash")),
    )
    op.create_index(
        "ix_tokens_verificacao_usuario_id", "tokens_verificacao", ["usuario_id"], unique=False
    )
    op.create_table(
        "bloqueios_agenda",
        sa.Column("profissional_id", sa.UUID(), nullable=False),
        sa.Column("inicio_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("fim_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("motivo", sa.String(length=200), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "criado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "atualizado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "fim_utc > inicio_utc", name=op.f("ck_bloqueios_agenda_intervalo_valido")
        ),
        sa.ForeignKeyConstraint(
            ["profissional_id"],
            ["perfis_profissional.usuario_id"],
            name=op.f("fk_bloqueios_agenda_profissional_id_perfis_profissional"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bloqueios_agenda")),
    )
    op.create_index(
        "ix_bloqueios_agenda_profissional_inicio",
        "bloqueios_agenda",
        ["profissional_id", "inicio_utc"],
        unique=False,
    )
    op.create_table(
        "compras_plano",
        sa.Column("paciente_id", sa.UUID(), nullable=False),
        sa.Column("profissional_id", sa.UUID(), nullable=False),
        sa.Column("plano_id", sa.UUID(), nullable=False),
        sa.Column("especialidade_id", sa.UUID(), nullable=False),
        sa.Column("quantidade_total", sa.SmallInteger(), nullable=False),
        sa.Column("valor_sessao_centavos", sa.Integer(), nullable=False),
        sa.Column("valor_total_centavos", sa.Integer(), nullable=False),
        sa.Column("percentual_comissao_aplicado", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDENTE", "ATIVA", "CANCELADA", "EXPIRADA", "CONCLUIDA", name="status_compra"
            ),
            server_default="PENDENTE",
            nullable=False,
        ),
        sa.Column("expira_em", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "criado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "atualizado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "quantidade_total > 0", name=op.f("ck_compras_plano_quantidade_positiva")
        ),
        sa.CheckConstraint(
            "valor_total_centavos >= 0", name=op.f("ck_compras_plano_valor_nao_negativo")
        ),
        sa.ForeignKeyConstraint(
            ["especialidade_id"],
            ["especialidades.id"],
            name=op.f("fk_compras_plano_especialidade_id_especialidades"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["paciente_id"],
            ["perfis_paciente.usuario_id"],
            name=op.f("fk_compras_plano_paciente_id_perfis_paciente"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["plano_id"],
            ["planos.id"],
            name=op.f("fk_compras_plano_plano_id_planos"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["profissional_id"],
            ["perfis_profissional.usuario_id"],
            name=op.f("fk_compras_plano_profissional_id_perfis_profissional"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_compras_plano")),
    )
    op.create_index("ix_compras_plano_paciente", "compras_plano", ["paciente_id"], unique=False)
    op.create_index(
        "ix_compras_plano_profissional", "compras_plano", ["profissional_id"], unique=False
    )
    op.create_table(
        "disponibilidades_recorrentes",
        sa.Column("profissional_id", sa.UUID(), nullable=False),
        sa.Column("dia_semana", sa.SmallInteger(), nullable=False),
        sa.Column("inicio_min", sa.SmallInteger(), nullable=False),
        sa.Column("fim_min", sa.SmallInteger(), nullable=False),
        sa.Column("vigencia_inicio", sa.Date(), nullable=False),
        sa.Column("vigencia_fim", sa.Date(), nullable=True),
        sa.Column("ativo", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "criado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "atualizado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "dia_semana BETWEEN 0 AND 6",
            name=op.f("ck_disponibilidades_recorrentes_dia_semana_0_6"),
        ),
        sa.CheckConstraint(
            "inicio_min >= 0 AND fim_min <= 1440 AND fim_min > inicio_min",
            name=op.f("ck_disponibilidades_recorrentes_janela_valida"),
        ),
        sa.CheckConstraint(
            "vigencia_fim IS NULL OR vigencia_fim >= vigencia_inicio",
            name=op.f("ck_disponibilidades_recorrentes_vigencia_coerente"),
        ),
        sa.ForeignKeyConstraint(
            ["profissional_id"],
            ["perfis_profissional.usuario_id"],
            name=op.f("fk_disponibilidades_recorrentes_profissional_id_perfis_profissional"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_disponibilidades_recorrentes")),
    )
    op.create_index(
        "ix_disponibilidades_profissional_dia",
        "disponibilidades_recorrentes",
        ["profissional_id", "dia_semana"],
        unique=False,
    )
    op.create_table(
        "pacientes_sintomas",
        sa.Column("paciente_id", sa.UUID(), nullable=False),
        sa.Column("sintoma_id", sa.UUID(), nullable=False),
        sa.Column("intensidade", sa.SmallInteger(), server_default="3", nullable=False),
        sa.Column("registrado_em", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "intensidade BETWEEN 1 AND 5", name=op.f("ck_pacientes_sintomas_intensidade_1_5")
        ),
        sa.ForeignKeyConstraint(
            ["paciente_id"],
            ["perfis_paciente.usuario_id"],
            name=op.f("fk_pacientes_sintomas_paciente_id_perfis_paciente"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["sintoma_id"],
            ["sintomas.id"],
            name=op.f("fk_pacientes_sintomas_sintoma_id_sintomas"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("paciente_id", "sintoma_id", name=op.f("pk_pacientes_sintomas")),
    )
    op.create_table(
        "profissionais_especialidades",
        sa.Column("profissional_id", sa.UUID(), nullable=False),
        sa.Column("especialidade_id", sa.UUID(), nullable=False),
        sa.Column("ordem", sa.SmallInteger(), nullable=False),
        sa.Column("preco_min_centavos", sa.Integer(), nullable=False),
        sa.Column("preco_padrao_centavos", sa.Integer(), nullable=False),
        sa.Column("preco_max_centavos", sa.Integer(), nullable=False),
        sa.Column("ativo", sa.Boolean(), server_default="true", nullable=False),
        sa.CheckConstraint(
            "ordem BETWEEN 1 AND 5", name=op.f("ck_profissionais_especialidades_ordem_1_5")
        ),
        sa.CheckConstraint(
            "preco_min_centavos > 0 AND preco_min_centavos <= preco_padrao_centavos AND preco_padrao_centavos <= preco_max_centavos",
            name=op.f("ck_profissionais_especialidades_faixa_preco_coerente"),
        ),
        sa.ForeignKeyConstraint(
            ["especialidade_id"],
            ["especialidades.id"],
            name=op.f("fk_profissionais_especialidades_especialidade_id_especialidades"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["profissional_id"],
            ["perfis_profissional.usuario_id"],
            name=op.f("fk_profissionais_especialidades_profissional_id_perfis_profissional"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "profissional_id", "especialidade_id", name=op.f("pk_profissionais_especialidades")
        ),
        sa.UniqueConstraint("profissional_id", "ordem", name="uq_profissional_ordem"),
    )
    op.create_index(
        "ix_profissionais_especialidades_especialidade_id",
        "profissionais_especialidades",
        ["especialidade_id"],
        unique=False,
    )
    op.create_table(
        "agendamentos",
        sa.Column("paciente_id", sa.UUID(), nullable=False),
        sa.Column("profissional_id", sa.UUID(), nullable=False),
        sa.Column("especialidade_id", sa.UUID(), nullable=False),
        sa.Column("inicio_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("fim_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("duracao_min", sa.SmallInteger(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDENTE_PAGAMENTO",
                "CONFIRMADO",
                "EM_ANDAMENTO",
                "REALIZADO",
                "CANCELADO_PACIENTE",
                "CANCELADO_PROFISSIONAL",
                "NO_SHOW_PACIENTE",
                "NO_SHOW_PROFISSIONAL",
                "EXPIRADO",
                name="status_agendamento",
            ),
            server_default="PENDENTE_PAGAMENTO",
            nullable=False,
        ),
        sa.Column("disponibilidade_origem_id", sa.UUID(), nullable=True),
        sa.Column("serie_recorrencia_id", sa.UUID(), nullable=True),
        sa.Column("valor_centavos", sa.Integer(), nullable=False),
        sa.Column("reserva_expira_em", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelado_em", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelado_por_id", sa.UUID(), nullable=True),
        sa.Column("motivo_cancelamento", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "criado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "atualizado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("duracao_min > 0", name=op.f("ck_agendamentos_duracao_positiva")),
        sa.CheckConstraint("fim_utc > inicio_utc", name=op.f("ck_agendamentos_intervalo_valido")),
        sa.CheckConstraint("valor_centavos >= 0", name=op.f("ck_agendamentos_valor_nao_negativo")),
        sa.ForeignKeyConstraint(
            ["disponibilidade_origem_id"],
            ["disponibilidades_recorrentes.id"],
            name=op.f("fk_agendamentos_disponibilidade_origem_id_disponibilidades_recorrentes"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["especialidade_id"],
            ["especialidades.id"],
            name=op.f("fk_agendamentos_especialidade_id_especialidades"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["paciente_id"],
            ["perfis_paciente.usuario_id"],
            name=op.f("fk_agendamentos_paciente_id_perfis_paciente"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["profissional_id"],
            ["perfis_profissional.usuario_id"],
            name=op.f("fk_agendamentos_profissional_id_perfis_profissional"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agendamentos")),
    )
    op.create_index(
        "ix_agendamentos_paciente_inicio",
        "agendamentos",
        ["paciente_id", "inicio_utc"],
        unique=False,
    )
    op.create_index(
        "ix_agendamentos_profissional_inicio",
        "agendamentos",
        ["profissional_id", "inicio_utc"],
        unique=False,
    )
    op.create_index(
        "ix_agendamentos_status_reserva",
        "agendamentos",
        ["status", "reserva_expira_em"],
        unique=False,
    )
    op.create_table(
        "pagamentos",
        sa.Column("compra_plano_id", sa.UUID(), nullable=False),
        sa.Column("provedor", sa.String(length=30), nullable=False),
        sa.Column("provedor_pagamento_id", sa.String(length=100), nullable=True),
        sa.Column(
            "metodo",
            sa.Enum("PIX", "CARTAO_CREDITO", "CARTAO_DEBITO", name="metodo_pagamento"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "CRIADO",
                "PENDENTE",
                "APROVADO",
                "RECUSADO",
                "ESTORNADO",
                "CANCELADO",
                "EXPIRADO",
                name="status_pagamento",
            ),
            server_default="CRIADO",
            nullable=False,
        ),
        sa.Column("valor_bruto_centavos", sa.Integer(), nullable=False),
        sa.Column("taxa_provedor_centavos", sa.Integer(), server_default="0", nullable=False),
        sa.Column("comissao_plataforma_centavos", sa.Integer(), server_default="0", nullable=False),
        sa.Column("imposto_retido_centavos", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "liquido_profissional_centavos", sa.Integer(), server_default="0", nullable=False
        ),
        sa.Column("moeda", sa.String(length=3), server_default="BRL", nullable=False),
        sa.Column("pix_qrcode", sa.Text(), nullable=True),
        sa.Column("pix_copia_cola", sa.Text(), nullable=True),
        sa.Column("pix_expira_em", sa.DateTime(timezone=True), nullable=True),
        sa.Column("chave_idempotencia", sa.String(length=80), nullable=False),
        sa.Column("payload_bruto", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("aprovado_em", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "criado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "atualizado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "taxa_provedor_centavos >= 0 AND comissao_plataforma_centavos >= 0 AND imposto_retido_centavos >= 0 AND liquido_profissional_centavos >= 0",
            name=op.f("ck_pagamentos_parcelas_nao_negativas"),
        ),
        sa.CheckConstraint(
            "valor_bruto_centavos >= 0", name=op.f("ck_pagamentos_bruto_nao_negativo")
        ),
        sa.ForeignKeyConstraint(
            ["compra_plano_id"],
            ["compras_plano.id"],
            name=op.f("fk_pagamentos_compra_plano_id_compras_plano"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pagamentos")),
        sa.UniqueConstraint("chave_idempotencia", name=op.f("uq_pagamentos_chave_idempotencia")),
        sa.UniqueConstraint(
            "provedor_pagamento_id", name=op.f("uq_pagamentos_provedor_pagamento_id")
        ),
    )
    op.create_index("ix_pagamentos_compra", "pagamentos", ["compra_plano_id"], unique=False)
    op.create_table(
        "avaliacoes",
        sa.Column("agendamento_id", sa.UUID(), nullable=False),
        sa.Column("nota_plataforma", sa.SmallInteger(), nullable=False),
        sa.Column("nota_profissional", sa.SmallInteger(), nullable=False),
        sa.Column("nota_proprio_cuidado", sa.SmallInteger(), nullable=False),
        sa.Column("comentario_plataforma", sa.Text(), nullable=True),
        sa.Column("comentario_profissional", sa.Text(), nullable=True),
        sa.Column("comentario_proprio_cuidado", sa.Text(), nullable=True),
        sa.Column("respondida_em", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "criado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "atualizado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "nota_plataforma BETWEEN 1 AND 5", name=op.f("ck_avaliacoes_nota_plataforma_1_5")
        ),
        sa.CheckConstraint(
            "nota_profissional BETWEEN 1 AND 5", name=op.f("ck_avaliacoes_nota_profissional_1_5")
        ),
        sa.CheckConstraint(
            "nota_proprio_cuidado BETWEEN 1 AND 5", name=op.f("ck_avaliacoes_nota_cuidado_1_5")
        ),
        sa.ForeignKeyConstraint(
            ["agendamento_id"],
            ["agendamentos.id"],
            name=op.f("fk_avaliacoes_agendamento_id_agendamentos"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_avaliacoes")),
        sa.UniqueConstraint("agendamento_id", name=op.f("uq_avaliacoes_agendamento_id")),
    )
    op.create_table(
        "creditos_sessao",
        sa.Column("compra_plano_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "DISPONIVEL",
                "RESERVADO",
                "CONSUMIDO",
                "EXPIRADO",
                "ESTORNADO",
                name="status_credito",
            ),
            server_default="DISPONIVEL",
            nullable=False,
        ),
        sa.Column("agendamento_id", sa.UUID(), nullable=True),
        sa.Column("consumido_em", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expira_em", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "criado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "atualizado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["agendamento_id"],
            ["agendamentos.id"],
            name=op.f("fk_creditos_sessao_agendamento_id_agendamentos"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["compra_plano_id"],
            ["compras_plano.id"],
            name=op.f("fk_creditos_sessao_compra_plano_id_compras_plano"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_creditos_sessao")),
        sa.UniqueConstraint("agendamento_id", name=op.f("uq_creditos_sessao_agendamento_id")),
    )
    op.create_index(
        "ix_creditos_sessao_compra_status",
        "creditos_sessao",
        ["compra_plano_id", "status"],
        unique=False,
    )
    op.create_table(
        "sessoes",
        sa.Column("agendamento_id", sa.UUID(), nullable=False),
        sa.Column("provedor_video", sa.String(length=30), nullable=False),
        sa.Column("sala_nome", sa.String(length=120), nullable=True),
        sa.Column("sala_url", sa.String(length=500), nullable=True),
        sa.Column("sala_expira_em", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "AGENDADA",
                "SALA_PRONTA",
                "LOBBY",
                "EM_ANDAMENTO",
                "ENCERRADA",
                "EXPIRADA",
                "CANCELADA",
                name="status_sessao",
            ),
            server_default="AGENDADA",
            nullable=False,
        ),
        sa.Column("link_enviado_em", sa.DateTime(timezone=True), nullable=True),
        sa.Column("profissional_entrou_em", sa.DateTime(timezone=True), nullable=True),
        sa.Column("paciente_entrou_em", sa.DateTime(timezone=True), nullable=True),
        sa.Column("paciente_admitido_em", sa.DateTime(timezone=True), nullable=True),
        sa.Column("iniciada_em", sa.DateTime(timezone=True), nullable=True),
        sa.Column("encerrada_em", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duracao_real_min", sa.SmallInteger(), nullable=True),
        sa.Column("chave_acesso_paciente_hash", sa.String(length=64), nullable=True),
        sa.Column("chave_acesso_profissional_hash", sa.String(length=64), nullable=True),
        sa.Column("transcricao_consentida", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "criado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "atualizado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["agendamento_id"],
            ["agendamentos.id"],
            name=op.f("fk_sessoes_agendamento_id_agendamentos"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sessoes")),
        sa.UniqueConstraint("agendamento_id", name=op.f("uq_sessoes_agendamento_id")),
    )
    op.create_index("ix_sessoes_status", "sessoes", ["status"], unique=False)
    op.create_table(
        "aceites_termo",
        sa.Column("usuario_id", sa.UUID(), nullable=False),
        sa.Column("termo_id", sa.UUID(), nullable=False),
        sa.Column("aceito_em", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ip", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("sessao_id", sa.UUID(), nullable=True),
        sa.Column("revogado_em", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["sessao_id"],
            ["sessoes.id"],
            name=op.f("fk_aceites_termo_sessao_id_sessoes"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["termo_id"],
            ["termos_versionados.id"],
            name=op.f("fk_aceites_termo_termo_id_termos_versionados"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["usuario_id"],
            ["usuarios.id"],
            name=op.f("fk_aceites_termo_usuario_id_usuarios"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_aceites_termo")),
    )
    op.create_index("ix_aceites_termo_sessao", "aceites_termo", ["sessao_id"], unique=False)
    op.create_index("ix_aceites_termo_usuario", "aceites_termo", ["usuario_id"], unique=False)
    op.create_table(
        "eventos_sessao",
        sa.Column("sessao_id", sa.UUID(), nullable=False),
        sa.Column(
            "tipo",
            sa.Enum(
                "SALA_CRIADA",
                "LINK_ENVIADO",
                "DISCLAIMER_ACEITO",
                "ENTROU_LOBBY",
                "ADMITIDO",
                "ENTROU_SALA",
                "SAIU",
                "ENCERRADA",
                name="tipo_evento_sessao",
            ),
            nullable=False,
        ),
        sa.Column("ator_id", sa.UUID(), nullable=True),
        sa.Column("ocorrido_em", sa.DateTime(timezone=True), nullable=False),
        sa.Column("metadados", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["sessao_id"],
            ["sessoes.id"],
            name=op.f("fk_eventos_sessao_sessao_id_sessoes"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_eventos_sessao")),
    )
    op.create_index(
        "ix_eventos_sessao_sessao_ocorrido",
        "eventos_sessao",
        ["sessao_id", "ocorrido_em"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_eventos_sessao_sessao_ocorrido", table_name="eventos_sessao")
    op.drop_table("eventos_sessao")
    op.drop_index("ix_aceites_termo_usuario", table_name="aceites_termo")
    op.drop_index("ix_aceites_termo_sessao", table_name="aceites_termo")
    op.drop_table("aceites_termo")
    op.drop_index("ix_sessoes_status", table_name="sessoes")
    op.drop_table("sessoes")
    op.drop_index("ix_creditos_sessao_compra_status", table_name="creditos_sessao")
    op.drop_table("creditos_sessao")
    op.drop_table("avaliacoes")
    op.drop_index("ix_pagamentos_compra", table_name="pagamentos")
    op.drop_table("pagamentos")
    op.drop_index("ix_agendamentos_status_reserva", table_name="agendamentos")
    op.drop_index("ix_agendamentos_profissional_inicio", table_name="agendamentos")
    op.drop_index("ix_agendamentos_paciente_inicio", table_name="agendamentos")
    op.drop_table("agendamentos")
    op.drop_index(
        "ix_profissionais_especialidades_especialidade_id",
        table_name="profissionais_especialidades",
    )
    op.drop_table("profissionais_especialidades")
    op.drop_table("pacientes_sintomas")
    op.drop_index("ix_disponibilidades_profissional_dia", table_name="disponibilidades_recorrentes")
    op.drop_table("disponibilidades_recorrentes")
    op.drop_index("ix_compras_plano_profissional", table_name="compras_plano")
    op.drop_index("ix_compras_plano_paciente", table_name="compras_plano")
    op.drop_table("compras_plano")
    op.drop_index("ix_bloqueios_agenda_profissional_inicio", table_name="bloqueios_agenda")
    op.drop_table("bloqueios_agenda")
    op.drop_index("ix_tokens_verificacao_usuario_id", table_name="tokens_verificacao")
    op.drop_table("tokens_verificacao")
    op.drop_index(
        "ix_sintomas_especialidades_especialidade_id", table_name="sintomas_especialidades"
    )
    op.drop_table("sintomas_especialidades")
    op.drop_index("ix_sessoes_login_usuario_id", table_name="sessoes_login")
    op.drop_table("sessoes_login")
    op.drop_table("perfis_profissional")
    op.drop_table("perfis_paciente")
    op.drop_index("ix_notificacoes_usuario", table_name="notificacoes")
    op.drop_index("ix_notificacoes_status_agendada", table_name="notificacoes")
    op.drop_table("notificacoes")
    op.drop_index("ix_eventos_pontuacao_usuario", table_name="eventos_pontuacao")
    op.drop_table("eventos_pontuacao")
    op.drop_table("usuarios")
    op.drop_index("ix_termos_versionados_tipo_vigente", table_name="termos_versionados")
    op.drop_table("termos_versionados")
    op.drop_table("sintomas")
    op.drop_table("planos")
    op.drop_index("ix_logs_auditoria_usuario_criado", table_name="logs_auditoria")
    op.drop_index("ix_logs_auditoria_entidade", table_name="logs_auditoria")
    op.drop_table("logs_auditoria")
    op.drop_table("especialidades")
    # ### end Alembic commands ###

    # op.drop_table() NÃO remove os tipos ENUM nativos que create_table criou.
    # Sem isto, um `downgrade base` seguido de `upgrade head` falha com
    # "type ... already exists" -- exatamente o ciclo que o CI executa.
    for tipo in TIPOS_ENUM:
        op.execute(f"DROP TYPE IF EXISTS {tipo}")
