"""papeis, permissoes e cadastro de menores

Revision ID: 0004
Revises: 0003
Create Date: 2026-08-13 01:03:56.157619+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


revision: str = "0004"
down_revision: str | None = "0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

#: Tipos ENUM nativos desta migration. create_table() os cria junto;
#: add_column() NÃO — e drop_* nunca os remove. Sem tratar os dois casos, o
#: ciclo downgrade/upgrade do CI quebra com "type already exists".
TIPOS_ENUM = ("status_paciente", "tipo_documento_responsavel")


def upgrade() -> None:
    # Valor novo num ENUM que já existe exige ALTER TYPE — o autogenerate não
    # detecta nem emite isso. Sem esta linha, gravar um aceite do tipo
    # CONSENT_RESPONSAVEL falha em runtime com DataError.
    op.execute("ALTER TYPE tipo_termo ADD VALUE IF NOT EXISTS 'CONSENT_RESPONSAVEL'")

    # `perfis_paciente.status` entra por add_column, que não cria o tipo.
    sa.Enum("ATIVO", "PENDENTE_RESPONSAVEL", "SUSPENSO", name="status_paciente").create(
        op.get_bind(), checkfirst=True
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "roles",
        sa.Column("nome", sa.String(length=60), nullable=False),
        sa.Column("descricao", sa.String(length=200), nullable=True),
        sa.Column("sistema", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "criado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "atualizado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_roles")),
        sa.UniqueConstraint("nome", name=op.f("uq_roles_nome")),
    )
    op.create_table(
        "role_permissions",
        sa.Column("role_id", sa.UUID(), nullable=False),
        sa.Column("modulo", sa.String(length=40), nullable=False),
        sa.Column("pode_criar", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("pode_ler", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("pode_atualizar", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("pode_deletar", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
            name=op.f("fk_role_permissions_role_id_roles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_role_permissions")),
        sa.UniqueConstraint("role_id", "modulo", name="uq_role_modulo"),
    )
    op.create_index("ix_role_permissions_role", "role_permissions", ["role_id"], unique=False)
    op.create_table(
        "acessos_documento",
        sa.Column("usuario_id", sa.UUID(), nullable=True),
        sa.Column("recurso", sa.String(length=60), nullable=False),
        sa.Column("recurso_id", sa.UUID(), nullable=False),
        sa.Column("motivo", sa.String(length=20), nullable=False),
        sa.Column("ip", sa.String(length=45), nullable=True),
        sa.Column("acessado_em", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["usuario_id"],
            ["usuarios.id"],
            name=op.f("fk_acessos_documento_usuario_id_usuarios"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_acessos_documento")),
    )
    op.create_index(
        "ix_acessos_documento_recurso", "acessos_documento", ["recurso", "recurso_id"], unique=False
    )
    op.create_index(
        "ix_acessos_documento_usuario",
        "acessos_documento",
        ["usuario_id", "acessado_em"],
        unique=False,
    )
    op.create_table(
        "verificacoes_responsavel",
        sa.Column("paciente_id", sa.UUID(), nullable=False),
        sa.Column("responsavel_nome", sa.String(length=150), nullable=False),
        sa.Column("responsavel_email", sa.String(length=255), nullable=True),
        sa.Column("responsavel_telefone_e164", sa.String(length=20), nullable=True),
        sa.Column("responsavel_usuario_id", sa.UUID(), nullable=True),
        sa.Column("parentesco", sa.String(length=40), nullable=True),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expira_em", sa.DateTime(timezone=True), nullable=False),
        sa.Column("enviado_em", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tentativas_envio", sa.Integer(), server_default="0", nullable=False),
        sa.Column("confirmado_em", sa.DateTime(timezone=True), nullable=True),
        sa.Column("confirmado_ip", sa.String(length=45), nullable=True),
        sa.Column("confirmado_user_agent", sa.Text(), nullable=True),
        sa.Column(
            "documento_tipo",
            sa.Enum(
                "RG",
                "CNH",
                "PASSAPORTE",
                "CERTIDAO_NASCIMENTO",
                "OUTRO",
                name="tipo_documento_responsavel",
            ),
            nullable=True,
        ),
        sa.Column("documento_chave", sa.String(length=300), nullable=True),
        sa.Column("documento_content_type", sa.String(length=60), nullable=True),
        sa.Column("documento_final", sa.String(length=8), nullable=True),
        sa.Column("documento_removido_em", sa.DateTime(timezone=True), nullable=True),
        sa.Column("recusado_em", sa.DateTime(timezone=True), nullable=True),
        sa.Column("motivo_recusa", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "criado_em", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "atualizado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["paciente_id"],
            ["perfis_paciente.usuario_id"],
            name=op.f("fk_verificacoes_responsavel_paciente_id_perfis_paciente"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["responsavel_usuario_id"],
            ["usuarios.id"],
            name=op.f("fk_verificacoes_responsavel_responsavel_usuario_id_usuarios"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_verificacoes_responsavel")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_verificacoes_responsavel_token_hash")),
    )
    op.create_index(
        "ix_verificacoes_responsavel_expira",
        "verificacoes_responsavel",
        ["expira_em", "confirmado_em"],
        unique=False,
    )
    op.create_index(
        "ix_verificacoes_responsavel_paciente",
        "verificacoes_responsavel",
        ["paciente_id"],
        unique=False,
    )
    op.add_column(
        "perfis_paciente",
        sa.Column(
            "status",
            postgresql.ENUM(
                "ATIVO",
                "PENDENTE_RESPONSAVEL",
                "SUSPENSO",
                name="status_paciente",
                create_type=False,
            ),
            server_default="ATIVO",
            nullable=False,
        ),
    )
    op.add_column("perfis_paciente", sa.Column("responsavel_usuario_id", sa.UUID(), nullable=True))
    op.add_column(
        "perfis_paciente",
        sa.Column("responsavel_confirmado_em", sa.DateTime(timezone=True), nullable=True),
    )
    op.create_index(
        "ix_perfis_paciente_responsavel",
        "perfis_paciente",
        ["responsavel_usuario_id"],
        unique=False,
    )
    op.create_index("ix_perfis_paciente_status", "perfis_paciente", ["status"], unique=False)
    op.create_foreign_key(
        op.f("fk_perfis_paciente_responsavel_usuario_id_usuarios"),
        "perfis_paciente",
        "usuarios",
        ["responsavel_usuario_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column("usuarios", sa.Column("role_id", sa.UUID(), nullable=True))
    op.add_column("usuarios", sa.Column("twofa_secret_cifrado", sa.LargeBinary(), nullable=True))
    op.add_column(
        "usuarios",
        sa.Column("twofa_habilitado", sa.Boolean(), server_default="false", nullable=False),
    )
    op.add_column("usuarios", sa.Column("openid_sub", sa.String(length=255), nullable=True))
    op.add_column("usuarios", sa.Column("openid_provider", sa.String(length=60), nullable=True))
    op.create_index("ix_usuarios_role", "usuarios", ["role_id"], unique=False)
    op.create_foreign_key(
        op.f("fk_usuarios_role_id_roles"),
        "usuarios",
        "roles",
        ["role_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_usuarios_role_id_roles"), "usuarios", type_="foreignkey")
    op.drop_index("ix_usuarios_role", table_name="usuarios")
    op.drop_column("usuarios", "openid_provider")
    op.drop_column("usuarios", "openid_sub")
    op.drop_column("usuarios", "twofa_habilitado")
    op.drop_column("usuarios", "twofa_secret_cifrado")
    op.drop_column("usuarios", "role_id")
    op.drop_constraint(
        op.f("fk_perfis_paciente_responsavel_usuario_id_usuarios"),
        "perfis_paciente",
        type_="foreignkey",
    )
    op.drop_index("ix_perfis_paciente_status", table_name="perfis_paciente")
    op.drop_index("ix_perfis_paciente_responsavel", table_name="perfis_paciente")
    op.drop_column("perfis_paciente", "responsavel_confirmado_em")
    op.drop_column("perfis_paciente", "responsavel_usuario_id")
    op.drop_column("perfis_paciente", "status")
    op.drop_index("ix_verificacoes_responsavel_paciente", table_name="verificacoes_responsavel")
    op.drop_index("ix_verificacoes_responsavel_expira", table_name="verificacoes_responsavel")
    op.drop_table("verificacoes_responsavel")
    op.drop_index("ix_acessos_documento_usuario", table_name="acessos_documento")
    op.drop_index("ix_acessos_documento_recurso", table_name="acessos_documento")
    op.drop_table("acessos_documento")
    op.drop_index("ix_role_permissions_role", table_name="role_permissions")
    op.drop_table("role_permissions")
    op.drop_table("roles")
    # ### end Alembic commands ###

    for tipo in TIPOS_ENUM:
        op.execute(f"DROP TYPE IF EXISTS {tipo}")
