name: Generate README Tree

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Generate README Tree
        uses: RavelloH/readme-tree@latest

      - name: Commit and Push changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Actions
          author_email: actions@github.com
          message: 'docs: generate README tree'
          add: 'README.md'
          continue-on-error: true
